# Generated by Django 5.1.2 on 2025-11-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmation',
            name='token',
            field=models.CharField(default='e1ccd30b834c4629897a06bce4c03cfd', max_length=64, unique=True),
        ),
    ]
