# Generated by Django 5.1.2 on 2025-11-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_emailconfirmation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmation',
            name='token',
            field=models.CharField(default='f181e4583fb4463b8670df22bf70e370', max_length=64, unique=True),
        ),
    ]
